import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    guides: [
        'overview',
        'initialization',
        'slot-naming',
        'animation-system',
        'options',
        'integrations',
        'spine-layout',
    ],
    api: [{ type: 'autogenerated', dirName: 'api' }],
};

export default sidebars;
